### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by ghost** [WolfgangMau/chamgo-qt#5]
Could you upload the binaries to Github please? The Dropbox links are dead.

**Comment by jaredvacanti** [comment]
Any chance these will be added to GitHub?

**Comment by Foul** [comment]
+1

**Comment by jamesgasek** [comment]
Bump

**Comment by rehall** [comment]
+1 ... what happened to the binaries?  
DropBox "didn't work for some reason".

**Comment by dend0r** [comment]
still dead links
